AWSTemplateFormatVersion: "2010-09-09"
Description: "ALB for Worker Nodes"

Parameters:
  VPCId:
    Type: String
  EnvironmentName:
    Description: Environment Name
    Type: String
  WebIngressSecurityGroup:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:
  ALB: # This is the Application Load Balancer that resides in front of the Worker Nodes
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${AWS::StackName}-ALB
      Scheme: internet-facing
      SecurityGroups:
      - !Ref WebIngressSecurityGroup
      Subnets:
      - !Ref PublicSubnet1
      - !Ref PublicSubnet2

  ALBTargetGroup: # This is the Target Group used by the ALB load balancer
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Name: !Sub ${AWS::StackName}-TgtGroup
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 4
      VpcId: !Ref VPCId
      Tags:
        -
          Key: Name
          Value: !Sub ${EnvironmentName}ALBTgtGroup

  ALBListener: # This is the ALB Listener used to access the Worker Node Web
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
    - ALB 
    - ALBTargetGroup
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  ALBListenerRule: # The ALB Listener rule that forwards all traffic destined for the environment to the appropriate Target Group
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: 
    - ALBListener
    - ALBTargetGroup
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref ALBTargetGroup
      Conditions:
      - Field: path-pattern
        Values:
        - "/*"
      ListenerArn: !Ref ALBListener
      Priority: 1

Outputs:
  ALBAddr:
    Description: Load balancer DNS address
    Value: !GetAtt ALB.DNSName
  ALBTargetGroup:
    Value: !Ref ALBTargetGroup