AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Type: String
  WorkerNodeLaunchTemplate:
    Type: String
  ALBTargetGroup:
    Type: String
  NumberOfWorkerNodes:
    Type: Number
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:
  ASGGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-ASG
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
        Version: '1'
<<<<<<< HEAD
      DesiredCapacity: 2
      MinSize: 2
=======
      DesiredCapacity: !Ref NumberOfWorkerNodes
      MinSize: 1
>>>>>>> 42e5c9240fba6e1019478da4b1e0982774900570
      MaxSize: 10
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      UpdatePolicy:
        AutoScalingRollingUpdate:
          MaxBatchSize: 2
          MinInstancesInService: 2
          MinSuccessfulInstancesPercent: 100
          PauseTime: PT5M
          # SuspendProcesses:
          #   - List of processes
          WaitOnResourceSignals: true
