AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Type: String
  WorkerNodeLaunchTemplate:
    Type: String
  ALBTargetGroup:
    Type: String
  NumberOfWorkerNodes:
    Type: Number
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:
  ASGGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-ASG
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
        Version: '1'
      DesiredCapacity: !Ref NumberOfWorkerNodes
      MinSize: 2
      MaxSize: 10
      TargetGroupARNs:
        - !Ref ALBTargetGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 2
        MinInstancesInService: 2
        MinSuccessfulInstancesPercent: 50
        PauseTime: PT5M
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
        WaitOnResourceSignals: true

  ASGScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: PercentChangeInCapacity
      AutoScalingGroupName: !Ref ASGGroup
      Cooldown: 300
      MinAdjustmentMagnitude: 2
      PolicyType: SimpleScaling
      ScalingAdjustment: 2