AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Type: String
  WorkerNodeLaunchTemplate:
    Type: String
  ALBTargetGroup:
    Type: String
  NumberOfWorkerNodes:
    Type: Number
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:
  ASGGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-ASG
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
        Version: '1'
      DesiredCapacity: !Ref NumberOfWorkerNodes
      MinSize: 2
      MaxSize: 10
      TargetGroupARNs:
        - !Ref ALBTargetGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 2
        MinInstancesInService: 2
        MinSuccessfulInstancesPercent: 50
        PauseTime: PT5M
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
        WaitOnResourceSignals: true

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref ASGGroup
      Cooldown: 300
      PolicyType: SimpleScaling
      ScalingAdjustment: 2
  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '20'
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
      Period: '60'  # Must be >= 60 for EC2
      AlarmActions:
      - Ref: ScaleUpPolicy
      Namespace: AWS/EC2
      Dimensions:
      - Name: ASGGroupName
        Value: !Ref ASGGroup
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization