AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Type: String
  WorkerNodeLaunchTemplate:
    Type: String
  ALBTargetGroup:
    Type: String
  # NumberOfWorkerNodes:
  #   Type: Number
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:
  ASGGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-ASG
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
        Version: '1'
      DesiredCapacity: '2'
      MinSize: '1'
      MaxSize: '6'
      LoadBalancerNames:
        - !Ref ALBTargetGroup
      Tags:
        -
          Key: Name
          PropogateAtLaunch: true
          Value: ${EnvironmentName}-Worker