# This will hook up the ALB to an existing domain registered in Route 53
AWSTemplateFormatVersion: "2010-09-09"
Description: "DNS Record Set connection for demo"

Parameters:
  ALBAddr:
    Description: The ALB DNS name
    Type: String
  ALBZoneId:
    Description: The Hosted Zone Id of the ALB
    Type: String
  EnvironmentName:
    Description: Environment name to be build
    Type: String
  R53HostedZoneId:
    Description: The Hosted Zone Id in R53
    Type: String
  R53Domain:
    Description: The Hosted Zone Domain
    Type: String
  JenkinsIp:
    Description: Jenkins Public IP Address
    Type: String

Resources:
  SiteDNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !Ref ALBAddr
        EvaluateTargetHealth: false
        HostedZoneId: !Ref ALBZoneId
      HostedZoneId: !Ref R53HostedZoneId
      Name: !Sub ${EnvironmentName}.${R53Domain}
      Type: A
  JenkinsDNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties: 
      ResourceRecords: 
      - !Ref JenkinsIp
      HostedZoneId: !Ref R53HostedZoneId
      Name: !Sub jenkins-${EnvironmentName}.${R53Domain}
      Type: A
      TTL: 900

Outputs:
  SiteDNS:
    Description: DNS name for application
    Value: !Ref SiteDNSRecordSet
  JenkinsDNS:
    Description: DNS name for application
    Value: !Ref JenkinsDNSRecordSet