AWSTemplateFormatVersion: "2010-09-09"
RootStack:
  Resources: 
    VPCStack:
      Type: AWS::CloudFormation::Stack
      Properties :
        TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/vpc2.yml
        TimeoutInMinutes: 5

  Parameters:
    EnvironmentName:
      Description: An environment name that is prefixed to resource names
      Type: String
      Default: Demo

    VpcCIDR:
      Description: Please enter the IP range (CIDR notation) for this VPC
      Type: String
      Default: 10.192.0.0/16

    PublicSubnet1CIDR:
      Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
      Type: String
      Default: 10.192.10.0/24

    PublicSubnet2CIDR:
      Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
      Type: String
      Default: 10.192.11.0/24

    PrivateSubnet1CIDR:
      Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
      Type: String
      Default: 10.192.20.0/24

    PrivateSubnet2CIDR:
      Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
      Type: String
      Default: 10.192.21.0/24