# This will create a Docker Worker Node
AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node"
Resources:
  # Will need adaption to get network details from VPC standup
  MyENI:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      Description: "Need static IP to allow Mgr node restart without breaking cluster"
      GroupSet: 
        - sg-0ffca9793f9a69a66
        - sg-d91becb0
      PrivateIpAddress: "172.31.32.21"
      SubnetId: subnet-746b951d
      Tags:
        -
          Key: Name
          Value: Demo-Work

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref MyENI
          DeviceIndex: 0
      IamInstanceProfile: !Ref WorkerProfile
      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum install -y docker jq;
            systemctl start docker;
            usermod -aG docker ec2-user;
           # aws ssm get-parameter --name /ClusterJoinCmd --region eu-west-2;
      Tags:
        -
          Key: Name
          Value: Demo-Work
# Assumes the existence of the role - which is created by the Docker Mgr instantiation
  WorkerProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: Access-SSM-Params-Profile-Worker
      Path: /
      Roles: 
        - EC2-SSM-Params-Role