# This will create a Docker Manager Node
AWSTemplateFormatVersion: "2010-09-09"
Description: Tiny Test Instance
Resources:

  # Will need adaption to get network details from VPC standup
  MyENI:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      Description: "Need to fix IP to advertise mgr status on"
      GroupSet: 
        - sg-0ffca9793f9a69a66
        - sg-d91becb0
      PrivateIpAddress: "172.31.32.20"
      SubnetId: subnet-746b951d

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref MyENI
          DeviceIndex: 0

      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum install -y docker;
            systemctl start docker;
            usermod -aG docker ec2-user;
            touch /home/ec2-user/userdata_ran;
      Tags:
        -
          Key: Name
          Value: TinyTestInstance