AWSTemplateFormatVersion: "2010-09-09"
Description: Role & policy to enable EC2 to access SSM Params via CLI
Resources:
  MgrRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2-SSM-Params-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for EC2 to access SSM Parameters via CLI
      MaxSessionDuration: 3600 # Role effective for 1 hour
      Path: /
      Policies: 
        - PolicyName: EC2-SSM-Params-Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: arn:aws:ssm:*:*:parameter/*
      Tags: 
        -
          Key: Name
          Value: Demo

 
