AWSTemplateFormatVersion: "2010-09-09"
Description: Role & policy to enable EC2 to use aws cli with SSM parameters
Resources:
  MgrRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2-SSM-Parameters-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: EC2 Docker Mgr Role to use CLI
      MaxSessionDuration: 3600 # Role effective for 1 hour
      Path: /
      Policies: 
        - PolicyName: EC2-SSM-Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: arn:aws:ssm:*:*:parameter/*
      Tags: 
        -
          Key: Name
          Value: EC2-Use-SSM-Parameters-Role

 
