AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Type: String
  DockerSecurityGroup:
    Type: String
  SSHIngressSecurityGroup:
    Type: String
  WebIngressSecurityGroup:
    Type: String
  PublicSubnet1:
    Type: String

Resources:
  WorkerNodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${EnvironmentName}WorkerNodeLaunchTemplate
      LaunchTemplateData:
        SecurityGroupIds:
          - !Ref DockerSecurityGroup
          - !Ref WebIngressSecurityGroup
          - !Ref SSHIngressSecurityGroup
        CreditSpecification: 
          CpuCredits: standard
        IamInstanceProfile:
          Name: !Ref WorkerProfile
        ImageId: ami-0389b2a3c4948b1a0
        InstanceType: t3a.nano
        KeyName: automation
        TagSpecifications:
          -
            ResourceType: instance
            Tags:
              - 
                Key: Name
                Value: !Sub ${EnvironmentName}-Worker
          -
            ResourceType: volume
            Tags:
              -
                Key: Name
                Value: !Sub ${EnvironmentName}
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash -xe
              yum install -y docker jq;
              systemctl start docker;
              usermod -aG docker ec2-user;
              $(aws ssm get-parameter --name /SwarmJoinCmd --region eu-west-2 | jq -r '.Parameter.Value');
              /opt/aws/bin/cfn-signal --exit-code 0 --resource DockerMgr --region ${AWS::Region} --stack ${AWS::StackName};

  WorkerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-EC2-SSM-Params-Worker-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for EC2 to read SSM Parameters via CLI
      MaxSessionDuration: 3600 # Role active for 1 hour (Implies no scaling after an hour - spot instances!)
      Path: /
      Policies: 
        - PolicyName: !Sub ${EnvironmentName}-EC2-SSM-Params-WorkerAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: arn:aws:ssm:*:*:parameter/*
      Tags: 
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-Worker
  
  WorkerProfile:
    DependsOn: WorkerRole
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub ${EnvironmentName}-Read-SSM-Params-Profile
      Path: /
      Roles: 
        - !Sub ${EnvironmentName}-EC2-SSM-Params-Worker-Role

Outputs:
  WorkerNodeLaunchTemplate:
    Description: A reference to the created Launch Template
    Value: !Ref WorkerNodeLaunchTemplate