AWSTemplateFormatVersion: "2010-09-09"
Description: Tiny Test Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum install -y docker;
            systemctl start docker;
            usermod -aG docker ec2-user;
            touch /home/ec2-user/userdata_ran;
      Tags:
        -
          Key: Name
          Value: TinyTestInstance
      SecurityGroupIds:
        - sg-d91becb0
        - sg-0ffca9793f9a69a66
      # This will need to come from network stack ultimately.
      # Think need fixed address or each instantiation will break cluster?
      NetworkInterface:
        Description: "Attempt to define a fixed private ip"
        DeviceIndex: 0
        GroupSet:
          - sg-0ffca9793f9a69a66
          - sg-d91becb0
        PrivateIpAddress: 172.31.32.20
        SubnetId: subnet-746b951d