AWSTemplateFormatVersion: "2010-09-09"
Description: Tiny Instance
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      Tags:
        -
          Key: "Name"
          Value: "TinyTestInstance"
      ImageId: "ami-0389b2a3c4948b1a0"
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard
      
  TinyTestSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      Tags:
        -
          Key: "Name"
          Value: "SSH-SG"
      VpcId: vpc-49ba5220
      GroupDescription: Tiny Test SG
      GroupName: TinyTestSG
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          Description: "SSH Inbound"
          FromPort: 22
          ToPort: 22
