AWSTemplateFormatVersion: "2010-09-09"
Description: Tiny Test Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          commands: "echo \"A command\" > test.txt"    
    Properties: 
      Tags:
        -
          Key: "Name"
          Value: "TinyTestInstance"
      ImageId: "ami-0389b2a3c4948b1a0"
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard