AWSTemplateFormatVersion: "2010-09-09"
Description: "Tiny Test Meta Version"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Install: ["Install"]
        Install:
          packages:
            yum:
              docker []
          files:
            /home/ec2-user/userdata_meta_ran:
              content:
                Fn::Join:
                  ["line", ["some text"], "last line"]
                mode: 000600
                owner: ec2-user
                group: ec2-user

    Properties:
      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            touch /home/ec2-user/userdata_ran;
            /opt/aws/bin/cfn-init -v
              --stack !Ref AWS::StackName
              --resource MyEC2Instance
              --configSets Install;
            usermod -aG docker ec2-user;
            docker run -d -p 80:80 --name nginx nginx;
            touch /home/ec2-user/meta_version_ran
      Tags:
        -
          Key: Name
          Value: TinyTestInstance
      SecurityGroupIds:
        - sg-d91becb0
        - sg-0ffca9793f9a69a66      