AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
  SSHIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  VPCId:
    Type: AWS::EC2::VPC::Id
  AMIId:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: JenkinsAMIId
  InstanceType:
    Type : String
    Default: t3a.small
    AllowedValues: 
      - t3a.nano
      - t3a.micro
      - t3a.small
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  JenkinsIPAllocationId:
    Type: String

Resources:

  JenkinsInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref JenkinsENI
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Jenkins
        - Key: Backup1357
          Value: !Sub ${EnvironmentName}-AMI
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            /opt/aws/bin/cfn-signal --exit-code 0 --resource JenkinsInstance --region ${AWS::Region} --stack ${AWS::StackName};

  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 8080, 8443 + SSH
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8443'
          ToPort: '8443'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-jenkins-sg

  JenkinsENI:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      GroupSet: 
        - !GetAtt JenkinsSecurityGroup.GroupId
        - !Ref SSHIngressSecurityGroup
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-JenkinsENI

  # This is pre-existing - if EIP is deleted will need AllocationId updating      
  JenkinsEIPAssoc:        
    Type: AWS::EC2::EIPAssociation
    Properties: 
      AllocationId: !Ref JenkinsIPAllocationId
      InstanceId: !Ref JenkinsInstance

Outputs:
  JenkinsPubIp:
    Description: IP address to access Jenkins
    Value: !GetAtt JenkinsInstance.PublicIp