AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnet2:
    Type: String
  SSHIngressSecurityGroup:
    Type: String
  VPCId:
    Type: String

Resources:
  JenkinsInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Properties:
      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      NetworkInterfaces:
         - NetworkInterfaceId: !Ref JenkinsENI
           DeviceIndex: 0
      Tags:
        -
          Key: Name
          Value: !Sub ${AWS::StackName}-Jenkins
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum -y update;
            wget -O /etc/yum.repos.d/jenkins.repo  http://pkg.jenkins-ci.org/redhat/jenkins.repo;
            rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key;
            yum install jenkins -y;
            systemctl start jenkins.service;
            systemctl enable jenkins.service;
            /opt/aws/bin/cfn-signal --exit-code 0 --resource JenkinsInstance --region ${AWS::Region} --stack ${AWS::StackName};

  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 8080, 8443
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8443'
          ToPort: '8443'
          CidrIp: 0.0.0.0/0          
      Tags:
        -
          Key: Name
          Value: jenkins-sg

  JenkinsENI:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      GroupSet: 
        - !GetAtt JenkinsSecurityGroup.GroupId
        - !Ref SSHIngressSecurityGroup
      SubnetId: !Ref PublicSubnet2
      Tags:
        -
          Key: Name
          Value: JenkinsENI

Outputs:

  JenkinsPubIp:
    Value: !GetAtt JenkinsInstance.PublicIp           