AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnet2:
    Type: String
  SSHIngressSecurityGroup:
    Type: String

Resources:
  JenkinsInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Properties:
      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      NetworkInterfaces:
         - NetworkInterfaceId: !Ref JenkinsENI
           DeviceIndex: 0       
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum -y update;
            /opt/aws/bin/cfn-signal --exit-code 0 --resource JenkinsInstance --region ${AWS::Region} --stack ${AWS::StackName};
      Tags:
        -
          Key: Name
          Value: !Sub ${AWS::StackName}-Jenkins

  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 8080, 8443 + SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8443'
          ToPort: '8443'
          CidrIp: 0.0.0.0/0          

      Tags:
        -
          Key: Name
          Value: !Sub ${AWS::StackName}-JenkinsSG

  JenkinsENI:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      GroupSet: 
        - !Ref JenkinsSecurityGroup
        - !Ref SSHIngressSecurityGroup
      SubnetId: !Ref PublicSubnet2
      Tags:
        -
          Key: Name
          Value: !Sub ${AWS::StackName}-JenkinsENI

Outputs:

  JenkinsPubIp:
    Value: !GetAtt JenkinsInstance.PublicIp           