AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaArn:
    Type: String 

Resources:  
  LambdaOnDelete:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Ref LambdaArn