AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String

Resources:
  AMICreateFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: cfn-demo-ianp
        S3Key: amicreate.zip
      Description: "Lambda to create ami from instance on stack delete"
      Handler: amicreate.lambda_handler
      ReservedConcurrentExecutions: 1
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Tags:
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-Lambda
      Timeout: 60

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: Demo-LambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - ec2:DescribeInstances
            - ec2:CreateTags
            - ec2:CreateImage
            - ssm:PutParameter
            Resource: "*"

Outputs:
  LambdaArn:
    Value: !GetAtt AMICreateFunction.Arn