AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Description: ARN that points to earlier created Lambda
  LambdaArn:
    Type: String 

# Execute the Lambda
Resources:  
  LambdaOnDelete:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Ref LambdaArn