# Seems to have an issue CFN can't delete instant fleet despite running
# with admin role it advises insufficient privilege for "describe-fleet"
# and "delete-fleet" But ... other Types do not launch!
AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  WorkerNodeLaunchTemplate:
    Type: String
  NumberOfWorkerNodes:
    Type: Number
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:
  LaunchFleet:
    Type: AWS::EC2::EC2Fleet
    Properties:
      LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: 
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
        Overrides:
            - SubnetId: !Ref PublicSubnet1
      - LaunchTemplateSpecification:
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
        Overrides:
            - SubnetId: !Ref PublicSubnet2        
      TargetCapacitySpecification:
        #SpotTargetCapacity: 1
        DefaultTargetCapacityType: spot
        TotalTargetCapacity: !Ref  NumberOfWorkerNodes
      Type: request
      TerminateInstancesWithExpiration: true  # Didn't launch without this in combo with Type: request
#
#