AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Type: String
  WorkerNodeLaunchTemplate:
    Type: String

Resources:
  LaunchFleet:
    Type: AWS::EC2::EC2Fleet
    Properties: 
      ExcessCapacityTerminationPolicy: termination
      LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: 
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
      ReplaceUnhealthyInstances: true
      TargetCapacitySpecification:
        DefaultTargetCapacityType: on-demand
        TotalTargetCapacity: 2