AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  WorkerNodeLaunchTemplate:
    Type: String
  NumberOfWorkerNodes:
    Type: Number

Resources:
  LaunchFleet:
    Type: AWS::EC2::EC2Fleet
    Properties:
      LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: 
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
      TargetCapacitySpecification:
        DefaultTargetCapacityType: on-demand
        TotalTargetCapacity: 1 #!Ref  NumberOfWorkerNodes
      Type: instant
    