AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  WorkerNodeLaunchTemplate:
    Type: String
  NumberOfWorkerNodes:
    Type: Number
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String

Resources:
  LaunchFleet:
    Type: AWS::EC2::EC2Fleet
    Properties:
      LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: 
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
        Overrides:
            - SubnetId: !Ref PublicSubnet1
      - LaunchTemplateSpecification:
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
        Overrides:
            - SubnetId: !Ref PublicSubnet2        
      TargetCapacitySpecification:
        DefaultTargetCapacityType: spot
        TotalTargetCapacity: !Ref  NumberOfWorkerNodes
      Type: maintain
      TerminateInstancesWithExpiration: true  # Didn't launch without this in combo with Type: request
      ExcessCapacityTerminationPolicy: termination
      SpotOptions:
        AllocationStrategy: diversified # Spread across subnets
      ReplaceUnhealthyInstances: true # Only seems to work with some configs