AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Description: Environment name for tags from root
    Type: String
  WorkerLaunchTemplate:
    Description: A reference to the created Launch Template
    Type: String
  NumberOfWorkerNodes:
    Description: Number of worker nodes requested
    Type: Number

Resources:
  Type: AWS::EC2::EC2Fleet
  Properties: 
    ExcessCapacityTerminationPolicy: termination
    LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: !Ref WorkerLaunchTemplate
    ReplaceUnhealthyInstances: true
    TargetCapacitySpecification:
      DefaultTargetCapacityType: on-demand
      TotalTargetCapacity: Integer 
    TerminateInstancesWithExpiration: Boolean
    Type: String
    ValidFrom: String
    ValidUntil: String