AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Parameters:
  EnvironmentName:
    Description: Environment name for tags from root
    Type: String
  WorkerNodeLaunchTemplate:
    Description: A reference to the created Launch Template
    Type: String
  NumberOfWorkerNodes:
    Description: Number of worker nodes requested
    Type: Number

Resources:
  LaunchFleet:
    Type: AWS::EC2::EC2Fleet
    Properties: 
      ExcessCapacityTerminationPolicy: termination
      LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: 
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
      ReplaceUnhealthyInstances: true
      TargetCapacitySpecification:
        DefaultTargetCapacityType: on-demand
        TotalTargetCapacity: !Ref NumberOfWorkerNodes