# Create standalone ENI
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: Environment Name for tags
    Type: String
  DockerSecurityGroup:
    Fn::GetAtt: [ VPCStack , Outputs.DockerSecurityGroup ]
  SSHIngressSecurityGroup:
    Fn::GetAtt: [ VPCStack , Outputs.SSHIngressSecurityGroup]
  PublicSubnet1:
    Fn::GetAtt: [VPCStack, Outputs.PublicSubnet1]

Resources:
  MyENI:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      Description: "Use to define static private ip for master node"
      GroupSet: 
        - !Ref DockerSecurityGroup
        - !Ref SSHIngressSecurityGroup
      PrivateIpAddress: "10.192.10.20"
      SubnetId: !Ref PublicSubnet1
      Tags:
        -
          Key: Name
          Value: !Sub ${EnvironmentName}-MasterNodeENI