# Create ENI to provide static IP to master node
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: Environment Name
    Type: String
  DockerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  SSHIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  WebIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateIP:
    Type: String

Resources:
  MgrENI:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      Description: "Used to define static private ip for master node"
      GroupSet: 
        - !Ref DockerSecurityGroup
        - !Ref SSHIngressSecurityGroup
        - !Ref WebIngressSecurityGroup
      PrivateIpAddress: !Ref PrivateIP
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-MasterNodeENI

Outputs:
  MgrENI:
    Description: Static IP for Docker Mgr Node
    Value: !Ref MgrENI