AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: Demo

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/vpc-nested.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  MgrENI:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/Master-ENI.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DockerSecurityGroup:
          Fn::GetAtt: [VPCStack, Outputs.DockerSecurityGroup]
        SSHIngressSecurityGroup:
          Fn::GetAtt: [VPCStack, Outputs.SSHIngressSecurityGroup]
        PublicSubnet1:
          Fn::GetAtt: [VPCStack, Outputs.PublicSubnet1]

  DockerMgr:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/EC2-DockerMgr.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        MgrENI:
          Fn::GetAtt: [MgrENI, Outputs.MgrENI]      