
# Demo: Not for production use, no security validation
AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  EnvironmentName:
    Description: A UNIQUE name for the environment
    Type: String
    Default: DEMO

  NumberOfWorkerNodes:
    Description: Number of worker nodes requested
    Type: Number
    Default: 2
    MaxValue: 10

  VpcCIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.11.0/24

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/vpc-nested.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR

  JenkinsInstance:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/jenkins.yml
      Parameters:
        EnvironmentName:
          !Ref EnvironmentName
        PublicSubnet2:
          Fn::GetAtt: [VPCStack, Outputs.PublicSubnet2]
        SSHIngressSecurityGroup:
          Fn::GetAtt: [VPCStack, Outputs.SSHIngressSecurityGroup]
        VPCId:
          Fn::GetAtt: [VPCStack, Outputs.VPC]

  # LambdaFunc:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/lambda.yml
  #     Paremeters:
  #       EnvironmentName:
  #         !Ref EnvironmentName