# Demo: Not for production use, no security validation
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: Demo

  NumberOfWorkerNodes:
    Description: Number of worker nodes requested
    Type: Number
    Default: 2
    MaxValue: 10

  VpcCIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: "** DO NOT CHANGE - USED AS CONSTANT **"
    Type: String
    Default: 10.192.21.0/24

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/vpc-nested.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  # MgrENI:
  #   Type: AWS::CloudFormation::Stack
  #   Properties: 
  #     TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/Master-ENI.yml
  #     Parameters:
  #       EnvironmentName: !Ref EnvironmentName
  #       DockerSecurityGroup:
  #         Fn::GetAtt: [VPCStack, Outputs.DockerSecurityGroup]
  #       SSHIngressSecurityGroup:
  #         Fn::GetAtt: [VPCStack, Outputs.SSHIngressSecurityGroup]
  #       PublicSubnet1:
  #         Fn::GetAtt: [VPCStack, Outputs.PublicSubnet1]

  # DockerMgr:
  #   Type: AWS::CloudFormation::Stack
  #   Properties: 
  #     TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/EC2-DockerMgr.yml
  #     Parameters:
  #       EnvironmentName: !Ref EnvironmentName
  #       MgrENI:
  #         Fn::GetAtt: [MgrENI, Outputs.MgrENI]

  WorkerNodeLaunchTemplate:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/EC2-WorkerLaunchTemplate.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DockerSecurityGroup:
          Fn::GetAtt: [VPCStack, Outputs.DockerSecurityGroup]
        SSHIngressSecurityGroup:
          Fn::GetAtt: [VPCStack, Outputs.SSHIngressSecurityGroup]
        WebIngressSecurityGroup:
          Fn::GetAtt: [VPCStack, Outputs.WebIngressSecurityGroup]
        PublicSubnet1:
          Fn::GetAtt: [VPCStack, Outputs.PublicSubnet1]

  LaunchFleet:
    DependsOn: WorkerNodeLaunchTemplate
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-eu-west-2.amazonaws.com/cfn-demo-ianp/LaunchFleet.yml
      Parameters:
        NumberOfWorkerNodes: !Ref NumberOfWorkerNodes
        WorkerNodeLaunchTemplate: 
          Fn::GetAtt: [WorkerNodeLaunchTemplate, Outputs.WorkerNodeLaunchTemplate]
        PublicSubnet1:
          Fn::GetAtt: [VPCStack, Outputs.PublicSubnet1]
        PublicSubnet2:
          Fn::GetAtt: [VPCStack, Outputs.PublicSubnet2]