# 
AWSTemplateFormatVersion: '2010-09-09'

Mappings: 
  Linux2Map: 
    us-east-1: 
      AMI: "ami-0323c3dd2da7fb37d"
    us-east-2:
      AMI: "ami-0f7919c33c90f5b58"
    us-west-1:
      AMI: "ami-06fcc1f0bc2c8943f"
    us-west-2:
      AMI: "ami-0d6621c01e8c2de2c"
    ca-central-1:
      AMI: "ami-054362537f5132ce2"
    eu-central-1:
      AMI: "ami-076431be05aaf8080"
    eu-west-1:
      AMI: "ami-06ce3edf0cff21f07"
    eu-west-2:
      AMI: "ami-01a6e31ac994bbc09"
    eu-west-3:
      AMI: "ami-00077e3fed5089981"
    eu-north-1:
      AMI: "ami-0b7a46b4bd694e8a6"

  # UbuntuMap:  # V18.04 LTS
  #   us-east-1: 
  #     AMI: "ami-085925f297f89fce1"
  #   us-east-2:
  #     AMI: "ami-07c1207a9d40bc3bd"
  #   us-west-1:
  #     AMI: "ami-0f56279347d2fa43e"
  #   us-west-2:
  #     AMI: "ami-003634241a8fcdec0"
  #   ca-central-1:
  #     AMI: "ami-0edd51cc29813e254"
  #   eu-central-1:
  #     AMI: "ami-0e342d72b12109f91"
  #   eu-west-1:
  #     AMI: "ami-0701e7be9b2a77600"
  #   eu-west-2:
  #     AMI: "ami-0eb89db7593b5d434"
  #   eu-west-3:
  #     AMI: "ami-08c757228751c5335"
  #   eu-north-1:
  #     AMI: "ami-050981837962d44ac"

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3a.nano
    AllowedValues:
    - m4.large
    - m5.large
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - t3.xlarge
    - t3.2xlarge
    - t3a.nano
    - t3a.micro
    - t3a.small
    - t3a.medium
    - t3a.large
    - t3a.xlarge
    - t3a.2xlarge

Resources:

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [Linux2Map, !Ref "AWS::Region", AMI]
      SecurityGroupIds: 
        - !Ref MySecurityGroup
      InstanceType: !Ref 'InstanceType'
      KeyName: automation
      # Tag the volume - seems long winded but couldn't find an easy way!
      # To make this work the ec2 instances needs a suitable temp role sts assume role etc
      # UserData:
      #   Fn::Base64:
      #     !Sub |
      #       #!/bin/bash -xe
      #       aws ec2 create-tags --resources $(aws ec2 describe-volumes --filters \
      #       Name=attachment.instance-id,Values=$(curl -s http://169.254.169.254/latest/meta-data/instance-id) \
      #       --query 'Volumes[*].[VolumeId]' --region=${AWS::Region} --out text | cut -f 1) --tags \
      #       Key=Name,Value=${AWS::StackName}-Vol --region ${AWS::Region};
      #       /opt/aws/bin/cfn-signal --exit-code 0 --resource MyInstance --region ${AWS::Region} --stack ${AWS::StackName};
      Tags:
        -
          Key: Name
          Value: !Sub ${AWS::StackName}

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Ingress
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0