# ** NOT WORKING! **
# This was an attempt to use Metadata but could not get to work
# as per examples from AWS
AWSTemplateFormatVersion: "2010-09-09"
Description: "Tiny Test Meta Version"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              docker []
          files:
            /home/ec2-user/userdata_meta_ran:
              content:
                Fn::Join:
                  ["line", ["some text"], "last line"]
                mode: 000600
                owner: ec2-user
                group: ec2-user

    Properties:
      ImageId: ami-0389b2a3c4948b1a0
      InstanceType: t3a.nano
      KeyName: automation
      CreditSpecification:
        CPUCredits: standard
      UserData:
        Fn::Base64:
        # The cfn-init call fails. Reports StackId not found but it is found and correct!?
          !Sub |
            #!/bin/bash -xe
            /opt/aws/bin/cfn-init -v -s ${AWS::StackId} -r MyEC2Instance;
            usermod -aG docker ec2-user;
            docker run -d -p 80:80 --name nginx nginx;
      Tags:
        -
          Key: Name
          Value: Demo
      SecurityGroupIds:
        - sg-d91becb0
        - sg-0ffca9793f9a69a66      