AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Resources:
  WorkerNodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-Template
      LaunchTemplateData: 
        CapacityReservationSpecification: 
          CapacityReservationPreference: none
        CreditSpecification: 
          CpuCredits: standard
        IamInstanceProfile:
          Name: !Ref WorkerProfile
        ImageId: ami-0389b2a3c4948b1a0
        InstanceType: t3a.nano
        KeyName: automation
        # SecurityGroupIds: 
        #   - !Ref SSHIngressSecurityGroup
        #   - !Ref WebIngressSecurityGroup
        #   - !Ref DockerSecurityGroup
        TagSpecifications:
          -
            ResourceType: instance
            Tags:
              - 
                Key: Name
                Value: !Ref AWS::StackName
          -
            ResourceType: volume
            Tags:
              -
                Key: Name
                Value: !Ref AWS::StackName
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash -xe
              yum update -y 

  WorkerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub EC2-SSM-Role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for EC2 to read SSM Parameters via CLI
      MaxSessionDuration: 3600 # Role active for 1 hour
      Path: /
      Policies: 
        - PolicyName: !Sub EC2-SSM-Policy-${AWS::StackName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: arn:aws:ssm:*:*:parameter/*
      Tags: 
        -
          Key: Name
          Value: !Ref AWS::StackName
  
  WorkerProfile:
    DependsOn: WorkerRole
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub Read-SSM-${AWS::StackName}
      Path: /
      Roles: 
        - !Ref WorkerRole

  LaunchFleet:
    Type: AWS::EC2::EC2Fleet
    Properties:
      LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: 
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
        Overrides:
          - 
            InstanceType: t3a.micro
            MaxPrice: 0.1
            Priority: 1
          - 
            InstanceType: t3.micro
            MaxPrice: 0.1
            Priority: 2
          - 
            InstanceType: t3a.small
            MaxPrice: 0.1
            Priority: 3        
          - 
            InstanceType: t3.small
            MaxPrice: 0.1
            Priority: 4
          - 
            InstanceType: m5.large
            MaxPrice: 0.1
            Priority: 5
          - 
            InstanceType: c5.large
            MaxPrice: 0.1
            Priority: 6                     
      TargetCapacitySpecification:
        TotalTargetCapacity: 2
        #OnDemandTargetCapacity: 1       # Something screwey happens when I add this line. Only ever creates 1 spot!
        DefaultTargetCapacityType: spot
      Type: maintain
      TerminateInstancesWithExpiration: true  # Didn't launch without this in combo with Type: request
      ExcessCapacityTerminationPolicy: termination
      SpotOptions:
        AllocationStrategy: diversified # Spread across subnets
      OnDemandOptions:
        MaxTotalPrice: 0.5
      ReplaceUnhealthyInstances: true # Only seems to work with some configs