AWSTemplateFormatVersion: "2010-09-09"
Description: "Docker Worker Node Launch Template"

Resources:
  WorkerNodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-Template
      LaunchTemplateData: 
        CapacityReservationSpecification: 
          CapacityReservationPreference: none
        CreditSpecification: 
          CpuCredits: standard
        IamInstanceProfile:
          Name: !Ref WorkerProfile
        ImageId: ami-0389b2a3c4948b1a0
        InstanceType: t3a.nano
        KeyName: automation
        # SecurityGroupIds: 
        #   - !Ref SSHIngressSecurityGroup
        #   - !Ref WebIngressSecurityGroup
        #   - !Ref DockerSecurityGroup
        TagSpecifications:
          -
            ResourceType: instance
            Tags:
              - 
                Key: Name
                Value: !Ref AWS::StackName
          -
            ResourceType: volume
            Tags:
              -
                Key: Name
                Value: !Ref AWS::StackName
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash -xe
              yum update -y 

  WorkerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2-SSM-Params-Worker-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role for EC2 to read SSM Parameters via CLI
      MaxSessionDuration: 3600 # Role active for 1 hour
      Path: /
      Policies: 
        - PolicyName: EC2-SSM-Params-WorkerAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: arn:aws:ssm:*:*:parameter/*
      Tags: 
        -
          Key: Name
          Value: !Ref AWS::StackName
  
  WorkerProfile:
    DependsOn: WorkerRole
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: Read-SSM-Params-Profile
      Path: /
      Roles: 
        - EC2-SSM-Params-Worker-Role

  LaunchFleet:
    Type: AWS::EC2::EC2Fleet
    Properties:
      LaunchTemplateConfigs: 
      - LaunchTemplateSpecification: 
          LaunchTemplateId: !Ref WorkerNodeLaunchTemplate
          Version: 1
        Overrides:
            - SubnetId: !Ref PublicSubnet1
      TargetCapacitySpecification:
        DefaultTargetCapacityType: spot
        TotalTargetCapacity: 1
      Type: maintain
      TerminateInstancesWithExpiration: true  # Didn't launch without this in combo with Type: request
      ExcessCapacityTerminationPolicy: termination
      SpotOptions:
        AllocationStrategy: diversified # Spread across subnets
      ReplaceUnhealthyInstances: true # Only seems to work with some configs